### ISSUE TITLE
Hard coded directory structure

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#112]
**Reported by hakalap on 2 Jun 2009 09:36 UTC**
I tried to setup maven2 directory structure when creating new Dynamic Web application. I get the following error:

```
org.eclipse.core.runtime.CoreException: Vaadin libraries installation failed
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.newCoreException(VaadinPluginUtil.java:399)
at com.vaadin.integration.eclipse.CoreFacetInstallDelegate.execute(CoreFacetInstallDelegate.java:115)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1394)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:401)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1134)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1070)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$5.run(FacetedProject.java:1052)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1800)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChanges(FacetedProject.java:1062)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.commitChanges(FacetedProjectWorkingCopy.java:1827)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard.performFinish(ModifyFacetedProjectWizard.java:388)
at org.eclipse.wst.web.ui.internal.wizards.NewProjectDataModelFacetWizard.performFinish(NewProjectDataModelFacetWizard.java:276)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard$3.run(ModifyFacetedProjectWizard.java:330)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1800)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard$4.run(ModifyFacetedProjectWizard.java:344)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: org.eclipse.core.runtime.CoreException: Failed to add Vaadin jar to project
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.newCoreException(VaadinPluginUtil.java:399)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.addVaadinLibrary(VaadinPluginUtil.java:432)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.ensureVaadinLibraries(VaadinPluginUtil.java:333)
at com.vaadin.integration.eclipse.CoreFacetInstallDelegate.execute(CoreFacetInstallDelegate.java:59)
... 14 more
Caused by: org.eclipse.core.runtime.CoreException: Failed to copy file to project
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.newCoreException(VaadinPluginUtil.java:399)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.copyPluginFileToProject(VaadinPluginUtil.java:257)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.addVaadinLibrary(VaadinPluginUtil.java:422)
... 16 more
Caused by: org.eclipse.core.internal.resources.ResourceException: Resource '/Test/WebContent/WEB-INF/lib' does not exist.
at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:317)
at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:194)
at org.eclipse.core.internal.resources.File.create(File.java:119)
at org.eclipse.core.internal.resources.File.create(File.java:186)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.copyPluginFileToProject(VaadinPluginUtil.java:254)
... 17 more


org.eclipse.core.runtime.CoreException: Failed to add Vaadin jar to project
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.newCoreException(VaadinPluginUtil.java:399)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.addVaadinLibrary(VaadinPluginUtil.java:432)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.ensureVaadinLibraries(VaadinPluginUtil.java:333)
at com.vaadin.integration.eclipse.CoreFacetInstallDelegate.execute(CoreFacetInstallDelegate.java:59)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1394)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:401)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1134)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1070)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$5.run(FacetedProject.java:1052)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1800)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChanges(FacetedProject.java:1062)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.commitChanges(FacetedProjectWorkingCopy.java:1827)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard.performFinish(ModifyFacetedProjectWizard.java:388)
at org.eclipse.wst.web.ui.internal.wizards.NewProjectDataModelFacetWizard.performFinish(NewProjectDataModelFacetWizard.java:276)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard$3.run(ModifyFacetedProjectWizard.java:330)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1800)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard$4.run(ModifyFacetedProjectWizard.java:344)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: org.eclipse.core.runtime.CoreException: Failed to copy file to project
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.newCoreException(VaadinPluginUtil.java:399)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.copyPluginFileToProject(VaadinPluginUtil.java:257)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.addVaadinLibrary(VaadinPluginUtil.java:422)
... 16 more
Caused by: org.eclipse.core.internal.resources.ResourceException: Resource '/Test/WebContent/WEB-INF/lib' does not exist.
at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:317)
at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:194)
at org.eclipse.core.internal.resources.File.create(File.java:119)
at org.eclipse.core.internal.resources.File.create(File.java:186)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.copyPluginFileToProject(VaadinPluginUtil.java:254)
... 17 more
```

Migrated-From: https://dev.vaadin.com/ticket/3046

**Comment by makoivis** [comment]
**Modified by hakalap on 2 Jun 2009 09:37 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Jun 2009 06:46 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 9 Jun 2009 08:08 UTC**
Fixed in [8161]: use Eclipse project paths for WebContent/\* in wizards and for Vaadin JAR installation/removal.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 9 Jun 2009 11:23 UTC**
"/src" directory is still hard coded and project creation fails if it is changed.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 10 Jun 2009 06:26 UTC**
Reference to fixed path "src" removed in [8165].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 24 Sep 2009 15:08 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
