### ISSUE TITLE
StackOverflowException when creating a new Theme.

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#116]
**Reported by Henrik Paul on 3 Jul 2009 10:25 UTC**
I tried to make a new theme for my Vaadin project, and I got this immediately after I chose the project in the popup:

```
[org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:167)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1561)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1585)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1566)
    at org.eclipse.swt.widgets.Combo.select(Combo.java:1496)
    at com.vaadin.integration.eclipse.wizards.NewThemeWizardPage.setProject(NewThemeWizardPage.java:131)
    at com.vaadin.integration.eclipse.wizards.NewThemeWizardPage.access$1(NewThemeWizardPage.java:117)
    at com.vaadin.integration.eclipse.wizards.NewThemeWizardPage$1.modifyText(NewThemeWizardPage.java:78)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:167)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1561)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1585)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1566)
    at org.eclipse.swt.widgets.Combo.select(Combo.java:1496)
[/snip](snip]
    at)
```

Migrated-From: https://dev.vaadin.com/ticket/3112

**Comment by makoivis** [comment]
**Comment by Artur Signell on 6 Jul 2009 07:28 UTC**
What version of the plugin are you using? Sounds suspiciously much like #3022, which has been fixed.

**Comment by makoivis** [comment]
**Comment by Henrik Paul on 6 Jul 2009 07:40 UTC**
0.9.0.200905211128, which is the same as in #3022. Sorry for the duplicate.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**
