### ISSUE TITLE
Error creating portlet.xml

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#136]
**Reported by Sami Ekblad on 14 Sep 2009 11:03 UTC**
Portlet configuration creation fails with following error:

Failed while installing Vaadin Eclipse Integration 0.1.
  Vaadin libraries installation failed
    Failed to write modified XML file portlet.xml
    java.lang.NullPointerException

System: OSX, Eclipse Ganymede JEE

Migrated-From: https://dev.vaadin.com/ticket/3357

**Comment by makoivis** [comment]
**Comment by Artur Signell on 14 Sep 2009 11:23 UTC**
See Window -> Show View -> Other -> Error log and copy/paste stacktrace here

**Comment by makoivis** [comment]
**Comment by Sami Ekblad on 17 Sep 2009 07:41 UTC**
eclipse.buildId=I20080617-2000
java.version=1.5.0_19
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86, WS=carbon, NL=en_US
Framework arguments:  -keyring /Users/se/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws carbon -arch x86 -data /Users/se/itmill/demo-workspace -keyring /Users/se/.eclipse_keyring -consoleLog -showlocation

Error
Thu Sep 17 10:39:18 EEST 2009
Vaadin libraries installation failed

org.eclipse.core.runtime.CoreException: Failed to write modified XML file portlet.xml
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.newCoreException(VaadinPluginUtil.java:395)
at com.vaadin.integration.eclipse.util.PortletConfigurationUtil.modifyXml(PortletConfigurationUtil.java:237)
at com.vaadin.integration.eclipse.util.PortletConfigurationUtil.addPortletToPortletsXml(PortletConfigurationUtil.java:139)
at com.vaadin.integration.eclipse.util.PortletConfigurationUtil.addPortlet(PortletConfigurationUtil.java:58)
at com.vaadin.integration.eclipse.CoreFacetInstallDelegate.execute(CoreFacetInstallDelegate.java:156)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1394)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:401)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1134)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1070)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$5.run(FacetedProject.java:1052)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1800)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChanges(FacetedProject.java:1062)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.commitChanges(FacetedProjectWorkingCopy.java:1834)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard.performFinish(ModifyFacetedProjectWizard.java:388)
at org.eclipse.wst.web.ui.internal.wizards.NewProjectDataModelFacetWizard.performFinish(NewProjectDataModelFacetWizard.java:276)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard$3.run(ModifyFacetedProjectWizard.java:330)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1800)
at org.eclipse.wst.common.project.facet.ui.ModifyFacetedProjectWizard$4.run(ModifyFacetedProjectWizard.java:344)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: javax.xml.transform.TransformerException: java.lang.NullPointerException
at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:670)
at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:300)
at com.vaadin.integration.eclipse.util.PortletConfigurationUtil.modifyXml(PortletConfigurationUtil.java:218)
... 17 more
Caused by: java.lang.NullPointerException
at com.sun.org.apache.xml.internal.serializer.SerializerBase.comment(SerializerBase.java:231)
at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.comment(ToUnknownStream.java:532)
at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:114)
at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:215)
at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:215)
at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:121)
at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:85)
at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:615)
at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:661)
... 19 more

**Comment by makoivis** [comment]
**Comment by Henri Sara on 18 Sep 2009 10:00 UTC**
The transformer fails when trying to update indentations and write the result in a file.

First attempt: changes in file handling in [8849].

**Comment by makoivis** [comment]
**Comment by Henri Sara on 21 Sep 2009 09:29 UTC**
Disable validation etc. in [NPEs are caused by what seems to be a bug in the JRE 1.5 Xerces library deferred document parsing. With JRE 1.6 there is no problem with these documents, and 1.5 seems to work after disabling deferred parsing the system works.

Disabled deferred parsing in [8859](8851].

The).

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
