### ISSUE TITLE
Widgetset compilation fails

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#206]
**Reported by Sami Ekblad on 11 Dec 2009 14:22 UTC**
Widgetset compilation fails with the 6.2 nightly Vaadin Eclipse plugin. Attached the full project for debugging.

Versions:
- Eclipse Galileo Java EE 20090920-1017
- Vaadin Eclipse Integration: 1.0.0.2009121110
- Vaadin-6.2.0.nightly-20091210-c10245
- Mac OS X 10.5.8
- Java 1.6.0

```
org.eclipse.core.internal.resources.ResourceException(/GoogleMap/WebContent/WEB-INF/lib)[566]: java.lang.IllegalStateException: zip file closed
    at java.util.zip.ZipFile.ensureOpen(ZipFile.java:518)
    at java.util.zip.ZipFile.entries(ZipFile.java:406)
    at java.util.jar.JarFile.entries(JarFile.java:215)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.isNeededForWidgetsetCompilation(Unknown Source)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.access$0(Unknown Source)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil$3.visit(Unknown Source)
    at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:108)
    at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:60)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:127)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:70)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:106)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:90)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getAvailableVaadinWidgetsetPackages(Unknown Source)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.compileWidgetset(Unknown Source)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsetIfNotRunning(Unknown Source)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsets(Unknown Source)
    at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(Unknown Source)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

Migrated-From: https://dev.vaadin.com/ticket/3844

**Comment by makoivis** [comment]
**Comment by Henri Sara on 18 Dec 2009 08:27 UTC**
In [10412], attempt to fix this by handling all JAR file closing in our plugin using the same mechanism, skipping explicit closing on mac and linux.

If this does not help, we may need to change the whole approach to reading JAR files in the plugin.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 10:02 UTC**
