### ISSUE TITLE
Plugin compile failures not shown in non-verbose mode

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#210]
**Reported by Marc Englund on 22 Dec 2009 13:16 UTC**
If the plugin is in the non-verbose mode (which is the default), it does not produce any kind of error message anywhere even if it fails completely.

E.g: Invalid gwt paths on build-path, compiler fails immediately, but produces no indication of this (other that completing abnormally quickly) - clicking the compile button just "compiles" for one or two seconds.

Not checking "Verbose compilation output" should not not mean "No compilation output" ;-)

Migrated-From: https://dev.vaadin.com/ticket/3903

**Comment by makoivis** [comment]
**Modified by Marc Englund on 22 Dec 2009 13:21 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 8 Jan 2010 14:03 UTC**
In [and [10654](10653]), set logLevel WARN and add some explicit compilation start/end messages (including the cancel case) when not in verbose mode.

Some of the new messages (compilation failed/canceled) also apply to the verbose mode.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 15 Jan 2010 06:41 UTC**
Still only

```
Compiling widgetset com.vaadin.directory.DirectoryApplicationWidgetset
Widgetset compilation failed
```

is shown in non verbose mode. Turning on verbose mode the errors are shown:

```
      [ERROR]  Internal compiler error
java.lang.UnsupportedClassVersionError: Bad version number in .class file
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
...
```

**Comment by makoivis** [comment]
**Comment by Henri Sara on 18 Jan 2010 12:40 UTC**
In [10765], more output (mostly warnings and errors, as well as some general messages) when not in verbose mode.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 10:02 UTC**
