### ISSUE TITLE
Widgetset creation fails when application is in default package

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#219]
**Reported by Artur Signell on 11 Jan 2010 06:23 UTC**
Widgetset creation fails if the application class is in the default package. The error is:

```
Java Model Exception: Java Model Status [name specified: .widgetset](Invalid)
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:784)
        at org.eclipse.jdt.internal.core.PackageFragmentRoot.createPackageFragment(PackageFragmentRoot.java:293)
        at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getWidgetSet(VaadinPluginUtil.java:1626)
        at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsets(WidgetsetBuildManager.java:433)
        at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:92)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

Migrated-From: https://dev.vaadin.com/ticket/3961

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:34 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 28 Aug 2014 08:46 UTC**
Milestone Plug-in for Eclipse backlog deleted
