### ISSUE TITLE
Error when trying to compile widgetset for the first time

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#220]
**Reported by Artur Signell on 11 Jan 2010 06:26 UTC**
After creating a Vaadin project and adding an addon jar I tried to compile the widgetset. The result was the following in the error log:

```
"No widget set found, com.virtuallypreinstalled.artur.cards.solitaire.widgetset.SolitaireWidgetset will be created..."
```

followed by

```
"Solitaire.java is read-only"
Java Model Exception: Java Model Status [is read-only](Solitaire.java)
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:784)
        at org.eclipse.jdt.internal.core.PackageFragmentRoot.createPackageFragment(PackageFragmentRoot.java:293)
        at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getWidgetSet(VaadinPluginUtil.java:1626)
        at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsets(WidgetsetBuildManager.java:433)
        at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:92)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

Solitaire.java is the application class.

Migrated-From: https://dev.vaadin.com/ticket/3962

**Comment by makoivis** [comment]
**Comment by Henri Sara on 18 Jan 2010 12:41 UTC**
Fixed problem in finding the package fragment root for an application in [10765].

**Comment by makoivis** [comment]
**Comment by Artur Signell on 25 Jan 2010 08:55 UTC**
Moving to correct milestone

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
