### ISSUE TITLE
Cannot create GAE project

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#245]
**Reported by Artur Signell on 18 Feb 2010 15:42 UTC**
When trying to create a Google App Engine project using Vaadin Eclipse plugin 1.2 everything seems to work but I am returned to the project wizard screen after clicking finish. 

The log says:

```
[...]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.readTextFromStream(VaadinPluginUtil.java:1283)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.readTextFromTemplate(VaadinPluginUtil.java:1510)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.ensureFileFromTemplate(VaadinPluginUtil.java:423)
at com.vaadin.integration.eclipse.util.GaeConfigurationUtil.createAppEngineWebXml(GaeConfigurationUtil.java:22)
at com.vaadin.integration.eclipse.CoreFacetInstallDelegate.execute(CoreFacetInstallDelegate.java:201)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1467)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:438)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1171)
at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1107)
```

Migrated-From: https://dev.vaadin.com/ticket/4201

**Comment by makoivis** [comment]
**Comment by Artur Signell on 19 Feb 2010 07:04 UTC**
Works after Eclipse restart.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 28 Aug 2014 08:46 UTC**
Milestone Plug-in for Eclipse backlog deleted
