### ISSUE TITLE
Created Vaadin & GAE project is broken

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#260]
**Reported by Henri Muurimaa on 23 Apr 2010 17:46 UTC**
When creating a new Vaadin/GAE project following the HOWTO http://vaadin.com/wiki/-/wiki/Main/Google%20AppEngine%20HOWTO the project is created with the following error:

```
The App Engine SDK 'C:\<workspace path>\<project name>\war' on the project's build path is not valid    GAEVTest        Unknown Google App Engine Problem
```

For some reason the default location for the GAE plugin is not used.

Problem can be corrected by pointing the project to the SDK manually, and then it runs, but accessing the app you get the following exception:

```
java.lang.NoClassDefFoundError: com/google/appengine/api/datastore/EntityNotFoundException
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.mortbay.jetty.servlet.Holder.newInstance(Holder.java:153)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:428)
    at org.mortbay.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:339)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:51)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.utils.jetty.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:70)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:349)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

This happens with Vaadin 6.3.0, GAE SDK 1.3.2 and 1.3.3 (latest), Google plugin for Eclipse 1.3.2.

This problem is also reported in the GAE forum: http://groups.google.com/group/google-appengine-java/browse_thread/thread/79555dd1bc974728/a47c461cb7f022b4?lnk=raot

Creating a regular GAE project (without Vaadin) using the above versions works fine.

Migrated-From: https://dev.vaadin.com/ticket/4596

**Comment by makoivis** [comment]
**Modified by Artur Signell on 23 Apr 2010 18:53 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Muurimaa on 23 Apr 2010 20:47 UTC**
The suggested workaround does not fix the problem: as mentioned in the description the SDK can be corrected in the preferences, but it does not change the exception when accessing the application.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 27 Apr 2010 15:55 UTC**
http://code.google.com/p/googleappengine/issues/detail?id=3154

Added workaround from the ticket. Did not test it, please do.

**Comment by makoivis** [comment]
**Comment by rishikhare on 30 Apr 2010 18:41 UTC**
Tested the work around. works correctly.

thanks

**Comment by makoivis** [comment]
**Comment by Henri Muurimaa on 1 May 2010 07:08 UTC**
I can also confirm the updated workaround.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 3 May 2010 07:56 UTC**
Added workaround to wiki page.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 13 Jan 2011 16:07 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 Aug 2011 14:34 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:34 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 28 Aug 2014 08:46 UTC**
Milestone Plug-in for Eclipse backlog deleted
