### ISSUE TITLE
NPE in widgetset compilation if the WebContent folder is not found

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#307]
**Reported by jotatu on 26 Aug 2010 05:56 UTC**
If one tries to compile a widgetset of the project which does not contain a WebContent folder, the compilation does not start and no error window is shown. Plug in just prints the stack trace into error log.

from error log:

```
java.lang.NullPointerException
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getWebContentFolder(VaadinPluginUtil.java:258)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.compileWidgetset(VaadinPluginUtil.java:2186)
at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsetIfNotRunning(WidgetsetBuildManager.java:566)
at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetset(WidgetsetBuildManager.java:634)
at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.compileFile(CompileWidgetsetHandler.java:147)
at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:84)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

Session Data:

```
eclipse.buildId=M20080911-1700
java.version=1.6.0_20
```

Migrated-From: https://dev.vaadin.com/ticket/5491

**Comment by makoivis** [comment]
**Comment by jotatu on 26 Aug 2010 06:26 UTC**
Root problem may not be the missing WebContent folder, since adding it does not help in this case. After searching the plug in source code I noticed that the problem is that the call 

```
IVirtualComponent component = ComponentCore.createComponent(project);
```

returns null.

**Comment by makoivis** [comment]
**Comment by jotatu on 26 Aug 2010 06:42 UTC**
Converting the project into Dynamic Web Project solved the problem in my case.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 19 Oct 2010 15:36 UTC**
Added better error messages in [15615] for the case when directories cannot be found. Typically cause by non-dynamic web projects or otherwise invalid projects.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 21 Oct 2010 07:10 UTC**
Reviewed by Henri Sara

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
