### ISSUE TITLE
Dragging Button generates AssertionErrors

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#320]
**Reported by John Ahlroos on 5 Oct 2010 07:46 UTC**
When dragging the Button around in an AbsoluteLayout the VDragAndDropManager generates a lot of AssertionErrors.

```
00:20:59.127 [ERROR] Uncaught exception escaped
java.lang.AssertionError: null  
at com.google.gwt.dom.client.Element$.as(Element.java:30)   
at com.vaadin.terminal.gwt.client.ui.dd.VDragAndDropManager$DefaultDragAndDropEventHandler.onPreviewNativeEvent(VDragAndDropManager.java:75)    
at com.google.gwt.user.client.Event$NativePreviewEvent.dispatch(Event.java:195)     
at com.google.gwt.user.client.Event$NativePreviewEvent.dispatch(Event.java:1)   
at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.fireEvent(HandlerManager.java:60)     
at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.access$1(HandlerManager.java:53)  
at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:178)    
at com.google.gwt.user.client.Event$NativePreviewEvent.fire(Event.java:87)  
at com.google.gwt.user.client.Event$NativePreviewEvent.access$4(Event.java:73)  
at com.google.gwt.user.client.Event$.fireNativePreviewEvent(Event.java:444)     
at com.google.gwt.user.client.DOM.previewEvent(DOM.java:1284)   
at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)     
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)    
at java.lang.reflect.Method.invoke(Method.java:592)     
at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)    
at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)   
at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)    
at com.google.gwt.dev.shell.BrowserChannel.reactToMessagesWhileWaitingForReturn(BrowserChannel.java:1714)   
at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:165)    
at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:120)    
at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:507)  
at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:264)    
at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)   
at com.google.gwt.core.client.impl.Impl.apply(Impl.java)    
at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:188)   
at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)     
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)    
at java.lang.reflect.Method.invoke(Method.java:592)     
at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)    
at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)   
at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)    
at com.google.gwt.dev.shell.BrowserChannel.reactToMessagesWhileWaitingForReturn(BrowserChannel.java:1714)   
at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:165)    
at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:120)    
at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:507)  
at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:264)    
at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)   
at com.google.gwt.core.client.impl.Impl.apply(Impl.java)    
at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:188)   
at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)     
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)    
at java.lang.reflect.Method.invoke(Method.java:592)     
at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)    
at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)   
at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)    
at com.google.gwt.dev.shell.BrowserChannel.reactToMessages(BrowserChannel.java:1669)    
at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:401)   
at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:222)     
at java.lang.Thread.run(Thread.java:595)
```

Migrated-From: https://dev.vaadin.com/ticket/5733

**Comment by makoivis** [comment]
**Comment by John Ahlroos on 7 Oct 2010 11:27 UTC**
Fixed in [15445]

**Comment by makoivis** [comment]
**Modified by Artur Signell on 10 Jun 2011 06:35 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
