### ISSUE TITLE
Compile widgetset throws exception

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#324]
**Reported by Artur Signell on 15 Oct 2010 10:03 UTC**
Every time a widgetset is compiled using the compile widgetset button an exception is thrown. The exception is not shown to the end user and the compilation seems to work.

```
!ENTRY org.eclipse.wst.validation 2 0 2010-10-15 13:01:08.875
!MESSAGE Resource '/aaa/WebContent/VAADIN/widgetsets' is not local.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource '/aaa/WebContent/VAADIN/widgetsets' is not local.
    at org.eclipse.core.internal.resources.Resource.checkLocal(Resource.java:338)
    at org.eclipse.core.internal.resources.Resource.checkAccessibleAndLocal(Resource.java:207)
    at org.eclipse.core.internal.resources.Resource.setSessionProperty(Resource.java:1854)
    at org.eclipse.wst.validation.internal.ValManager.putValProperty(ValManager.java:927)
    at org.eclipse.wst.validation.internal.ValManager.accept(ValManager.java:819)
    at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:669)
    at org.eclipse.wst.validation.internal.ValBuilderJob$Visitor.visit(ValBuilderJob.java:321)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:68)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:79)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:79)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:79)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
    at org.eclipse.wst.validation.internal.ValBuilderJob.deltaBuild(ValBuilderJob.java:211)
    at org.eclipse.wst.validation.internal.ValBuilderJob.run(ValBuilderJob.java:179)
    at org.eclipse.wst.validation.internal.ValBuilderJob.runInWorkspace(ValBuilderJob.java:126)
    at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Migrated-From: https://dev.vaadin.com/ticket/5809

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Oct 2010 10:03 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 2 Nov 2010 16:04 UTC**
Fixed in [15832].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:43 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
