### ISSUE TITLE
Exception when trying to compile widgetset

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#325]
**Reported by Artur Signell on 17 Oct 2010 12:37 UTC**

```
java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.core.resources.IFolder
    at com.vaadin.integration.eclipse.util.ProjectUtil.getWebContentFolder(ProjectUtil.java:118)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.compileWidgetset(VaadinPluginUtil.java:1391)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsetIfNotRunning(WidgetsetBuildManager.java:570)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetset(WidgetsetBuildManager.java:638)
    at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.compileFile(CompileWidgetsetHandler.java:175)
    at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:98)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

Also seen in the forum (old post): https://vaadin.com/forum/-/message_boards/message/121852

Migrated-From: https://dev.vaadin.com/ticket/5817

**Comment by makoivis** [comment]
**Comment by Artur Signell on 17 Oct 2010 13:57 UTC**
I could only reproduce it in a Eclipse Galileo installation that had other issues also. Same workspace works fine in Helios SR-1.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 17 Oct 2010 14:26 UTC**
The actual cause of the problem:

A missing <wb-resource deploy-path="/" source-path="/WebContent"/>

row in .settings/org.eclipse.wst.common.component

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**
