### ISSUE TITLE
Eclipse plugin does not find add-on jar-files from the classpath

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#328]
**Reported by jotatu on 18 Oct 2010 10:52 UTC**
For some reason eclipse plugin tries to find add-on jars from c:\ although the workspace is in different place: c:\Users\user\Desktop\WS\

"Could not access JAR when searching for widgetsets"

```
java.io.FileNotFoundException: C:\XXX\WebContent\WEB-INF\lib\icepush.jar (Mritetty polkua ei lydy)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(Unknown Source)
at java.util.jar.JarFile.<init>(Unknown Source)
at java.util.jar.JarFile.<init>(Unknown Source)
at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
at sun.net.www.protocol.jar.JarURLConnection.getJarFile(Unknown Source)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.isNeededForWidgetsetCompilation(VaadinPluginUtil.java:1062)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getAvailableVaadinWidgetsetPackages(VaadinPluginUtil.java:1211)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.compileWidgetset(VaadinPluginUtil.java:1403)
at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsetIfNotRunning(WidgetsetBuildManager.java:570)
at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetset(WidgetsetBuildManager.java:638)
at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.compileFile(CompileWidgetsetHandler.java:177)
at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:74)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

Migrated-From: https://dev.vaadin.com/ticket/5832

**Comment by makoivis** [comment]
**Comment by Henri Sara on 18 Oct 2010 11:31 UTC**
Classpath container contents (including WEB-INF/lib contents) were referenced with workspace relative paths, which could lead to them not being found when compiling a widgetset.

Fixed in [15600].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
