### ISSUE TITLE
NPE when project contains broken JRE/JDK reference

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#346]
**Reported by Artur Signell on 17 Jan 2011 15:51 UTC**

```
java.lang.NullPointerException
    at com.vaadin.integration.eclipse.util.ProjectUtil.findProjectVaadinJarPath(ProjectUtil.java:343)
    at com.vaadin.integration.eclipse.util.ProjectUtil.isVaadin62(ProjectUtil.java:385)
    at com.vaadin.integration.eclipse.util.WidgetsetUtil.isWidgetsetDirty(WidgetsetUtil.java:582)
```

Migrated-From: https://dev.vaadin.com/ticket/6296

**Comment by makoivis** [comment]
**Comment by Artur Signell on 17 Jan 2011 15:51 UTC**
Fixed in [16910].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 17 Jan 2011 15:53 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 17 Jan 2011 16:07 UTC**
Fixed similar issues in [16912].

**Comment by makoivis** [comment]
**Comment by Artur Signell on 18 Feb 2011 14:24 UTC**
Reviewed by Henri Sara

**Comment by makoivis** [comment]
**Modified by Artur Signell on 2 May 2011 05:53 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
