### ISSUE TITLE
New Vaadin Project wizard gets stuck on Installing Vaadin Plug-in for Eclipse facet...

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#399]
**Reported by Artur Signell on 20 Dec 2011 08:52 UTC**
Creating a new Vaadin project gets stuck on "Installing Vaadin Plug-in for Eclipse facet...". Happens (at least) on Windows when trying to create a new Vaadin project while having Tomcat running with  other Vaadin projects deployed to it (same Vaadin version used for new project as in the other projects, target runtime in the new project is Tomcat).

Also reported in the forum at https://vaadin.com/forum/-/message_boards/view_message/507152 

Output from jstack from the relevant thread:

```
"ModalContext" prio=6 tid=0x00000000074aa000 nid=0x1974 in Object.wait() [0x0000000017c2e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000e588fb68> (a java.lang.Object)
        at java.lang.Object.wait(Object.java:485)
        at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:272)
        - locked <0x00000000e588fb68> (a java.lang.Object)
        at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:199)
        at org.eclipse.core.internal.jobs.JobManager.yieldRule(JobManager.java:1398)
        at org.eclipse.core.internal.jobs.InternalJob.yieldRule(InternalJob.java:600)
        at org.eclipse.core.runtime.jobs.Job.yieldRule(Job.java:709)
        at org.eclipse.wst.common.componentcore.internal.builder.DependencyGraphImpl.waitForAllUpdates(DependencyGraphImpl.java:691)
        at org.eclipse.wst.common.componentcore.internal.builder.DependencyGraphImpl.getReferencingComponents(DependencyGraphImpl.java:126)
        at org.eclipse.wst.common.componentcore.internal.builder.DependencyGraphImpl.getReferencingComponents(DependencyGraphImpl.java:116)
        at org.eclipse.wst.common.componentcore.internal.resources.VirtualComponent.getReferencingComponents(VirtualComponent.java:577)
        at org.eclipse.jst.j2ee.project.facet.EarFacetValidator.validate(EarFacetValidator.java:77)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectValidationBuilder.build(FacetedProjectValidationBuilder.java:132)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:256)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:394)
        at org.eclipse.core.internal.resources.Project$1.run(Project.java:618)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)
        at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:597)
        at org.eclipse.core.internal.resources.Project.build(Project.java:114)
        at com.vaadin.integration.eclipse.util.ProjectDependencyManager.addVaadinLibrary(ProjectDependencyManager.java:242)
        at com.vaadin.integration.eclipse.util.ProjectDependencyManager.ensureVaadinLibraries(ProjectDependencyManager.java:68)
        at com.vaadin.integration.eclipse.CoreFacetInstallDelegate.execute(CoreFacetInstallDelegate.java:137)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1477)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:441)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1181)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$5.run(FacetedProject.java:1099)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChanges(FacetedProject.java:1109)
        at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.commitChanges(FacetedProjectWorkingCopy.java:2020)
```

Migrated-From: https://dev.vaadin.com/ticket/8157

**Comment by makoivis** [comment]
**Comment by Henri Sara on 20 Dec 2011 10:50 UTC**
Attempted fix to review and test in [22457].

**Comment by makoivis** [comment]
**Comment by Henri Sara on 21 Dec 2011 07:44 UTC**
Closing as probably fixed - please reopen if reproduced.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
