### ISSUE TITLE
NullPointerException in Eclipse Vaadin plugin when enabling facet

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#418]
**Reported by ringerc on 5 Jun 2012 04:18 UTC**
When I added the Vaadin facet to an existing Maven based project in Eclipse, after editing my pom.xml to include the vaadin deps and compiler plugin and adding the Vaadin servlet to my web.xml, the plugin threw an NPE.

I disabled the JavaServer Faces facet at the same time, in case that matters.

I'm using the Vaadin plugin from Marketplace, installed today:

```
  Vaadin Plug-in for Eclipse    2.0.1.201105170102  com.vaadin.integration.eclipse.feature.group    Vaadin Ltd
```

```
An internal error occurred during: "Compiling wigetset for project xxx...".

java.lang.NullPointerException
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getSubClasses(VaadinPluginUtil.java:589)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getApplicationClasses(VaadinPluginUtil.java:612)
    at com.vaadin.integration.eclipse.util.WidgetsetUtil.getWidgetSet(WidgetsetUtil.java:708)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsets(WidgetsetBuildManager.java:453)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.internalCompile(WidgetsetBuildManager.java:394)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.access$1(WidgetsetBuildManager.java:390)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager$CompileWidgetsetJob.run(WidgetsetBuildManager.java:267)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)


```

```
eclipse.buildId=M20120208-0800
java.version=1.7.0_b147-icedtea
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product
```

Migrated-From: https://dev.vaadin.com/ticket/8897

**Comment by makoivis** [comment]
**Comment by ringerc on 5 Jun 2012 05:08 UTC**
I haven't been able to reproduce this on an imported copy of the vaadin archetype, so it's not clear what exactly went wrong. Hopefully the stack trace will tell you something.

I clicked the "Additional configuration available..." link when adding the facet and used the plugin to generate a skeleton Vaadin application class and configuration for the project.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:24 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:40 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 17 Dec 2014 06:01 UTC**
A lot of tickets have been left hanging in the issue tracker through the years. Some of them are still relevant, some of them have been fixed a long time ago and some are no longer valid. To get a better look on what is important and still relevant, we are closing old tickets which have not been touched in a long time.

No further work will be done on this ticket unless someone indicates that it's still relevant. 

If this ticket is still relevant to you, please reopen it.
