### ISSUE TITLE
Widgetset Compilation Fails If Build Path Contains Class Folder Entry

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#472]
**Reported by phancox on 31 Oct 2012 04:03 UTC**
Compiling the Widgetset using the Eclipse plugin fails if the Vaadin project has a class folder added to the build path.  e.g., library of common routines.

```
!ENTRY com.vaadin.integration.eclipse 4 0 2012-10-31 14:49:28.762
!MESSAGE Widgetset compilation failed
!STACK 0
java.lang.IllegalArgumentException: Path must include project and resource name: /AppSrvcs
    at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
    at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2163)
    at org.eclipse.core.internal.resources.Container.getFolder(Container.java:222)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getRawLocation(VaadinPluginUtil.java:1014)
    at com.vaadin.integration.eclipse.util.VaadinPluginUtil.getProjectBaseClasspath(VaadinPluginUtil.java:860)
    at com.vaadin.integration.eclipse.util.WidgetsetUtil.buildCommonArgs(WidgetsetUtil.java:319)
    at com.vaadin.integration.eclipse.util.WidgetsetUtil.compileWidgetset(WidgetsetUtil.java:135)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsetIfNotRunning(WidgetsetBuildManager.java:579)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsets(WidgetsetBuildManager.java:480)
    at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.compileFile(CompileWidgetsetHandler.java:169)
    at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:93)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

Migrated-From: https://dev.vaadin.com/ticket/10099

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:24 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 16 Dec 2014 21:59 UTC**
A lot of tickets have been left hanging in the issue tracker through the years. Some of them are still relevant, some of them have been fixed a long time ago and some are no longer valid. To get a better look on what is important and still relevant, we are closing old tickets which have not been touched in a long time.

No further work will be done on this ticket unless someone indicates that it's still relevant. 

If this ticket is still relevant to you, please reopen it.
