### ISSUE TITLE
Widgetset compilation failed

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#487]
**Reported by xylifyx on 11 Dec 2012 07:58 UTC**
Vaadin eclipse plugin version: 2.0.1.201211280958

```
java.lang.NullPointerException
    at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:92)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

```
eclipse.buildId=I20120608-1400
java.version=1.6.0_35
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/emartino/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/emartino/.eclipse_keyring -showlocation
```

Migrated-From: https://dev.vaadin.com/ticket/10495

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:04 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:40 UTC**

**Comment by makoivis** [comment]
**Comment by miki on 28 Sep 2014 18:22 UTC**
I managed to get the same error in the latest (20140901) version of the plugin:

```
!ENTRY com.vaadin.integration.eclipse 4 0 2014-09-27 21:28:17.674
!MESSAGE Widgetset compilation failed
!STACK 0
java.lang.NullPointerException at
com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:85) at
org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

It happened when compiling widgetset for a Maven project that was imported from git that did not have the Vaadin facet marked in Project Facets. I was able to reproduce it a number of times. '''Setting Vaadin as a Project Facet fixed the issue.'''

Suggested solution: display a more meaningful error message (e.g. ''Cannot compile widgetset. Check if Vaadin is a Project Facet of projectname''), or ideally prompt to change the facet by showing a link to project settings in the error dialog.
