### ISSUE TITLE
NPE in new Vaadin Widget wizard with Maven projects

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#517]
**Reported by Joonas Lehtinen on 2 Mar 2013 10:14 UTC**
= Test =
- Create new Maven project from vaadin-application in Eclipse
- Select File > New > Other... > Vaadin Widget
- NPE

= Implication =

It is not possible to create widgets in Eclipse if you are using Maven. There are no easy to follow examples for creating widget by hand (without the wizard), so in practice this makes custom widget development very hard with Maven projects.

= Tested on = 

Eclipse Juno SR1, vaadin-applciation-archetype 7.0.1 with the following plugins:
  Eclipse EGit  2.2.0.201212191850-r    org.eclipse.egit.feature.group  Eclipse EGit
  Eclipse IDE for Java EE Developers    1.5.1.20121004-1506 epp.package.jee null
  Eclipse JGit  2.2.0.201212191850-r    org.eclipse.jgit.feature.group  Eclipse JGit
  Google App Engine Java SDK 1.7.4  1.7.4   com.google.appengine.eclipse.sdkbundle.feature.feature.group    Google, Inc.
  Google App Engine Tools for Android   3.1.3.v201212122042-rel-r42 com.google.gdt.eclipse.mobile.android.feature.feature.group Google, Inc.
  Google Plugin for Eclipse 4.2 3.1.3.v201212122042-rel-r42 com.google.gdt.eclipse.suite.e42.feature.feature.group  Google, Inc.
  Google Web Toolkit SDK 2.5.0  2.5.0.v201212122042-rel-r42 com.google.gwt.eclipse.sdkbundle.e42.feature.feature.group  Google, Inc.
  GWT Designer Core 2.6.0.r42x201206111222  com.google.gdt.eclipse.designer.hosted.feature.feature.group    Google, Inc.
  GWT Designer Editor   2.6.0.r42x201206111227  com.google.gdt.eclipse.designer.editor.feature.feature.group    Google, Inc.
  GWT Designer GPE  2.6.0.r42x201206111341  com.google.gdt.eclipse.designer.gpe.feature.feature.group   Google, Inc.
  JRebel    5.1.3.SR1-201302011351  org.zeroturnaround.eclipse.feature.feature.group    ZeroTurnaround
  JRebel for Java EE    5.1.3.SR1-201302011351  org.zeroturnaround.eclipse.wtp.feature.feature.group    ZeroTurnaround
  m2e - Maven Integration for Eclipse   1.2.0.20120903-1050 org.eclipse.m2e.feature.feature.group   Eclipse.org - m2e
  m2e connector for mavenarchiver pom properties    0.15.0.201207090125-signed-201209140800 org.sonatype.m2e.mavenarchiver.feature.feature.group    Sonatype, Inc.
  m2e-wtp - Maven Integration for WTP (Incubation)  0.16.0.20120914-0945    org.eclipse.m2e.wtp.feature.feature.group   Eclipse.org - m2e-wtp
  Maven SCM Handler for EGit    0.14.0.201207041402 org.sonatype.m2e.egit.feature.feature.group Sonatype, Inc.
  Migration Dummy (Debugger Integration)    5.1.3.SR1-201302011351  org.zeroturnaround.eclipse.debug.feature.feature.group  ZeroTurnaround
  Migration Dummy (Embedded JRebel) 5.1.3.SR1-201302011351  org.zeroturnaround.eclipse.embedder.feature.feature.group   ZeroTurnaround
  Migration Dummy (JRebel Remoting) 5.1.3.SR1-201302011351  org.zeroturnaround.eclipse.remoting.feature.feature.group   ZeroTurnaround
  Vaadin Plug-in for Eclipse    2.1.0.201302071057  com.vaadin.integration.eclipse.feature.group    Vaadin Ltd
  Xtend SDK 2.3.1.v201208210947 org.eclipse.xtend.sdk.feature.group Eclipse Xtend

= Exception =

java.lang.NullPointerException
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.selectTemplate(NewComponentWizardPage.java:282)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.updateTemplateCombo(NewComponentWizardPage.java:198)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.createClientSideControls(NewComponentWizardPage.java:276)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.createControl(NewComponentWizardPage.java:238)
    at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:174)
    at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:736)
    at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1182)
    at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1241)
    at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1238)
    at org.eclipse.jface.wizard.WizardDialog$8.run(WizardDialog.java:1227)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1225)
    at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:915)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:428)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:624)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4134)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1458)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1271)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3980)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3619)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:259)
    at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:279)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:229)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:210)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:131)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:171)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:276)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:494)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:545)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:366)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:313)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:82)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1072)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4133)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1458)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
    at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1495)
    at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Tree.sendKeyEvent(Tree.java:2582)
    at org.eclipse.swt.widgets.Control.keyDown(Control.java:2371)
    at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:600)
    at org.eclipse.swt.widgets.Tree.keyDown(Tree.java:1966)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5495)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:221)
    at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2102)
    at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2299)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5557)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5002)
    at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5151)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
    at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3616)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1029)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:923)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)

Migrated-From: http://dev.vaadin.com//ticket/11223

**Comment by makoivis** [comment]
**Comment by Joonas Lehtinen on 2 Mar 2013 11:09 UTC**
Started building vaadin-archetype-widget for Vaadin 7. While existence of an up-to-date widget archetype would lower the priority for this issue a bit, it should be fixed asap in any case as people need to be able to add widgets to their maven based application projects in eclipse.

**Comment by makoivis** [comment]
**Comment by Joonas Lehtinen on 2 Mar 2013 17:23 UTC**
Created a separate ticket for vaadin-archetype-widget Vaadin 7 support: #11225

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:04 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 5 Dec 2014 18:08 UTC**
A lot of tickets have been left hanging in the issue tracker through the years. Some of them are still relevant, some of them have been fixed a long time ago and some are no longer valid. To get a better look on what is important and still relevant, we are closing old tickets which have not been touched in a long time.

No further work will be done on this ticket unless someone indicates that it's still relevant.

If this ticket is still relevant to you, please reopen it.
