### ISSUE TITLE
Dev mode does not start with eclipse plugin

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#522]
**Reported by Joonas Lehtinen on 25 Mar 2013 17:31 UTC**
DevMode does not seem to work with Eclipse plugin. Tested Vaadin versions 7.0.0 and 7.0.3 with Eclipse Juno on Mac using both JDK 1.6.0 and JDK 1.7.0 and Eclipse plugin version 2.1.0.201303071057. 

In all cases the dev mode reports:

Failed to load module 'com.example.devmodetest.DevmodetestWidgetset' from user agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.35 (KHTML, like Gecko) Chrome/27.0.1448.0 Safari/537.35' at localhost:49349
java.lang.NoSuchFieldError: reportUnusedDeclaredThrownExceptionIncludeDocCommentReference
    at com.google.gwt.dev.javac.JdtCompiler.getCompilerOptions(JdtCompiler.java:411)
    at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.<init>(JdtCompiler.java:228)
    at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:717)
    at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:248)
    at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:463)
    at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:388)
    at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:373)
    at com.google.gwt.dev.DevModeBase$UiBrowserWidgetHostImpl.createModuleSpaceHost(DevModeBase.java:108)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:197)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:526)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:680)

For steps to reproduce the issue, see the attached video.

Migrated-From: http://dev.vaadin.com//ticket/11417

**Comment by makoivis** [comment]
**Modified by Joonas Lehtinen on 25 Mar 2013 18:03 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:04 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 5 Mar 2014 14:23 UTC**
This ticket has been open for a long time without any action. If you have additional information and this is still an issue for you, please comment and/or reopen.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**
