### ISSUE TITLE
The AddonStylesImporter failed to create then addons.scss

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#538]
**Reported by Artur Signell on 2 May 2013 16:18 UTC**
An error occurs when creating a new project:

```
java.lang.Error: The AddonStylesImporter failed to create then addons.scss file with the return code 1
    at com.vaadin.integration.eclipse.builder.AddonStylesImporter.run(AddonStylesImporter.java:95)
    at com.vaadin.integration.eclipse.builder.AddonStylesBuilder.build(AddonStylesBuilder.java:32)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Refreshing the project produces the same error but creates an empty addon.scss. The theme however does not import addons.scss

The error is repeated on every save etc. Why would it even try to update addons.scss when I save? It should update it when a jar is added to the project.

Migrated-From: http://dev.vaadin.com//ticket/11760

**Comment by makoivis** [comment]
**Comment by Artur Signell on 3 May 2013 08:34 UTC**
This can be reproduced only by creating a Vaadin 7.0.5 project and then updating the version to 7.1-SNAPSHOT. The problem is in IvyDE which does not properly update the widgetset-compile configuration but leaves old 7.0.5 jars there. Obviously, the methods that the addon.scss generator tries to use are not available there.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**
