### ISSUE TITLE
"IllegalStateException: zip file closed" when compiling both theme and widget set

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#555]
**Reported by Artur Signell on 14 Jun 2013 06:26 UTC**

```
java.lang.IllegalStateException: zip file closed
    at java.util.zip.ZipFile.ensureOpen(ZipFile.java:415)
    at java.util.zip.ZipFile.entries(ZipFile.java:310)
    at java.util.jar.JarFile.entries(JarFile.java:220)
    at com.vaadin.integration.eclipse.util.WidgetsetUtil.isNeededForWidgetsetCompilation(WidgetsetUtil.java:611)
    at com.vaadin.integration.eclipse.util.WidgetsetUtil.getAvailableVaadinWidgetsetPackages(WidgetsetUtil.java:1147)
    at com.vaadin.integration.eclipse.util.WidgetsetUtil.buildCommonArgs(WidgetsetUtil.java:408)
    at com.vaadin.integration.eclipse.util.WidgetsetUtil.compileWidgetset(WidgetsetUtil.java:161)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsetIfNotRunning(WidgetsetBuildManager.java:579)
    at com.vaadin.integration.eclipse.builder.WidgetsetBuildManager.compileWidgetsets(WidgetsetBuildManager.java:480)
    at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler.compileFile(CompileWidgetsetHandler.java:154)
    at com.vaadin.integration.eclipse.handlers.CompileWidgetsetHandler$1.run(CompileWidgetsetHandler.java:107)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

Migrated-From: http://dev.vaadin.com//ticket/12078

**Comment by makoivis** [comment]
**Comment by Artur Signell on 14 Jun 2013 06:26 UTC**
"Compile theme" works as excepted

"Compile widgetset" works as expected

but compiling both at the same time fails

**Comment by makoivis** [comment]
**Comment by Henri Sara on 14 Jun 2013 06:55 UTC**
This may be platform specific (Windows), resulting from theme and widgetset compilation occurring simultaneously.

The solution is to use locking, in this case locking the whole project.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:43 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
