### ISSUE TITLE
Vaadin Eclipse Plugin throws NullPointerException when creating Widget after using "Go Into"

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#557]
**Reported by Patrik Lindstrom on 18 Jun 2013 11:20 UTC**
Vaadin's Eclipse Plugin throws a NullPointerException, displayed in an alert window, when attempting to create a new Widget. This happens only after having selected a project (or other resource) and selecting "Go Into" from the right-click menu. As soon as normal overview is resumed, the null pointer exception goes away.

Steps to reproduce:

1) create new project

2) right click to 'Go Into' project

3) attempt to create new Vaadin Widget

Migrated-From: http://dev.vaadin.com//ticket/12096

**Comment by makoivis** [comment]
**Comment by macquail on 24 Oct 2013 07:35 UTC**
Similiar thing happens when Project Explorer displays working sets as top level.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:03 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:40 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 17 Dec 2014 16:59 UTC**
A lot of tickets have been left hanging in the issue tracker through the years. Some of them are still relevant, some of them have been fixed a long time ago and some are no longer valid. To get a better look on what is important and still relevant, we are closing old tickets which have not been touched in a long time.

No further work will be done on this ticket unless someone indicates that it's still relevant. 

If this ticket is still relevant to you, please reopen it.

**Comment by makoivis** [comment]
**Comment by dennis.flottmann on 2 Feb 2015 08:31 UTC**
I am still having the same problem. Using Liferay IDE (Luna 4.2 SR2) and additionaly installed latest vaadin plugin (v 2.3.1.201411271550 - Installed by dropping the link into the eclipse workspace). 
Creating new vaadin widget-project is not possible.
Using the "next" button after selecting vaadin - widget in the wizard leads to following error in the log and the wizard does not proceed:

Eclipse Error Log: Unhandled event loop exception in plugin org.eclispe.ui

Stacktrace: 
java.lang.NullPointerException
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.selectTemplate(NewComponentWizardPage.java:282)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.updateTemplateCombo(NewComponentWizardPage.java:198)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.createClientSideControls(NewComponentWizardPage.java:276)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.createControl(NewComponentWizardPage.java:238)
    at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
    at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:759)
    at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1210)
    at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1271)
    at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1268)
    at org.eclipse.jface.wizard.WizardDialog$8.run(WizardDialog.java:1257)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1254)
    at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:942)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:434)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
    at org.eclipse.jface.window.Window.open(Window.java:808)
    at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:269)
    at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:290)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
    at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
    at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:159)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by makoivis** [comment]
**Modified by dennis.flottmann on 2 Feb 2015 08:35 UTC**

**Comment by makoivis** [comment]
**Comment by dennis.flottmann on 2 Feb 2015 09:57 UTC**
Fixed by adding project facet vaadin 7 to portlet project in workspace.
The Requirement of a vaadin project in the same workspace as the new widget-project should be (better) documented and/or handled.
