### ISSUE TITLE
VisualDesigner can't be opened on Win7 with Eclipse Kepler

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#561]
**Reported by Artur Signell on 27 Jun 2013 18:40 UTC**
Unable to create class 'org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor' from bundle '689'

```
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.swt.internal.mozilla.init.GREVersionRange
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:63)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:877)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:857)
    at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:119)
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:333)
    at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:254)
...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.swt.internal.mozilla.init.GREVersionRange
    at org.eclipse.swt.browser.Mozilla.InitDiscoverXULRunner(Mozilla.java:1759)
    at org.eclipse.swt.browser.Mozilla.LoadLibraries(Mozilla.java:617)
    at org.eclipse.swt.browser.Mozilla.create(Mozilla.java:682)
    at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
    at com.vaadin.visualdesigner.eclipse.editors.VaadinEditor.createBrowser(VaadinEditor.java:223)
    at com.vaadin.visualdesigner.eclipse.editors.VaadinEditor.createVisualEditorPage(VaadinEditor.java:208)
```

Migrated-From: http://dev.vaadin.com//ticket/12141

**Comment by makoivis** [comment]
**Comment by Artur Signell on 27 Jun 2013 18:42 UTC**
See https://issues.jboss.org/browse/JBIDE-14749

**Comment by makoivis** [comment]
**Comment by darrelln09 on 20 Sep 2013 21:09 UTC**
I see the linked issue in JBoss has now been resolved. Perhaps that solution would help with the resolution of this defect.

**Comment by makoivis** [comment]
**Comment by hofmanndavid on 26 Sep 2013 15:28 UTC**
+1

**Comment by makoivis** [comment]
**Comment by hofmanndavid on 8 Oct 2013 19:37 UTC**
To workaround this as suggested in the forums add this to your ecilpse.ini file and it 

-Dorg.eclipse.swt.browser.XULRunnerPath=C:\

**Comment by makoivis** [comment]
**Comment by Sebastian.Dietrich on 29 Oct 2013 09:24 UTC**
Workaround does not work for me. Neither when pointing to an existing XULRunner or just C:\ as suggested in the forums.
Seems as if users of 64bit Eclipse Kepler will not be able to run the VisualDesigner.
See https://vaadin.com/forum#!/thread/295862

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:03 UTC**

**Comment by makoivis** [comment]
**Comment by tatacalu on 5 Mar 2014 13:10 UTC**
+1 Hi Guys, are there plans for fixing this issue in the near future?

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Comment by tracme on 22 Aug 2014 11:52 UTC**
I've got the same problem (Win7 64Bil Eclipse Luna 4.4.; Java 8.11). Adding -Dorg.eclipse.swt.browser.XULRunnerPath=C:\ to eclipse.ini didn't solve my problem either. Can you please help?

Errorlog:
!MESSAGE Unable to create class 'org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor' from bundle '707'
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.swt.internal.mozilla.init.GREVersionRange
(...)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.swt.internal.mozilla.init.GREVersionRange
    at org.eclipse.swt.browser.Mozilla.InitDiscoverXULRunner(Mozilla.java:1838)
(...)

THANKS!!!
