### ISSUE TITLE
"New Vaadin Widget" wizard throws NPE when no project selected

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#563]
**Reported by Johannes Dahlstrom on 12 Jul 2013 10:02 UTC**
Selecting "Vaadin Widget" in the New dialog, then clicking "Next" does nothing if there's no project selected in the Package Explorer; double-clicking the "Vaadin Widget" gives a "Problem Occurred" dialog informing that a NullPointerException was thrown. If another option is then chosen in the New dialog without closing and reopening the dialog, the Vaadin Widget wizard is shown but cannot be completed.

The error log gives the following stack trace:

```
java.lang.NullPointerException
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.selectTemplate(NewComponentWizardPage.java:282)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.updateTemplateCombo(NewComponentWizardPage.java:198)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.createClientSideControls(NewComponentWizardPage.java:276)
    at com.vaadin.integration.eclipse.wizards.NewComponentWizardPage.createControl(NewComponentWizardPage.java:238)
    at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1246)
    at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1238)
    at org.eclipse.jface.wizard.WizardDialog$8.run(WizardDialog.java:1227)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1225)
    at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:915)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:428)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:624)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1276)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3562)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3186)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:259)
    at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:279)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:231)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:212)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:131)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:171)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:277)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:496)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:547)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:368)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:314)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:83)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1484)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1275)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1300)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1285)
    at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1312)
    at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:748)
    at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3050)
    at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:741)
    at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1773)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:5116)
    at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:3476)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4377)
    at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
    at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:8317)
    at org.eclipse.swt.widgets.Display.eventProc(Display.java:1193)
    at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
    at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2342)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3184)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```

Migrated-From: http://dev.vaadin.com//ticket/12216

**Comment by makoivis** [comment]
**Comment by Johannes Dahlstrom on 12 Jul 2013 11:34 UTC**
Apparently the wizard is only supposed to work with an existing project; this is fine but should be documented in the UI and of course not throw.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:03 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:40 UTC**

**Comment by makoivis** [comment]
**Comment by tibo74 on 17 Dec 2014 16:09 UTC**
I have exactly the same problem: impossible to create a new widget using the plugin wizard, with the same stack trace, even when my project is selected (right click on the project, like described in the Vaadin book https://vaadin.com/book/-/page/gwt.eclipse.html)

Environment:
- Windows 7
- java project with Vaadin 7.3.5 (without using Maven)
- Eclipse Java EE IDE for Web Developers

```
Version: Luna Service Release 1 (4.4.1)
Build id: 20140925-1800
E4 RCP Patch (bugzillas 445122) 1.0.0   org.eclipse.e4.rcp.R441patch.feature.group  Eclipse.org
Eclipse Git Team Provider   3.5.2.201411120430-r    org.eclipse.egit.feature.group  Eclipse EGit
Eclipse IDE for Java EE Developers  4.4.1.20140925-1820 epp.package.jee null
Java implementation of Git  3.5.2.201411120430-r    org.eclipse.jgit.feature.group  Eclipse JGit
Maven SCM Handler for EGit  0.14.0.201406241643 org.sonatype.m2e.egit.feature.feature.group Sonatype, Inc.
Vaadin Plug-in for Eclipse  2.3.1.201411271550  com.vaadin.integration.eclipse.feature.group    Vaadin Ltd
```

**Comment by makoivis** [comment]
**Comment by proaccountapp on 10 Jul 2015 08:29 UTC**
Updated prioritization date.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 10 Jul 2015 08:58 UTC**
Verified on Luna: one of the last fall-backs in finding the project Vaadin version (used with Ivy, at least) uses VaadinPluginUtil.isVaadinJar(IPath) which tries to open a JAR file to check its manifest. This fails as in Luna the URL should start with "jar://" rather than just "jar:" (a change in behavior from older Eclipse versions, most likely from Juno to Kepler).

In addition to this, NewComponentWizardPage.updateTemplateCombo() (and perhaps setProjectInternal()) should handle and report better the case where the project Vaadin version could not be retrieved.

**Comment by makoivis** [comment]
**Modified by Henri Sara on 14 Jul 2015 12:06 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 14 Jul 2015 12:06 UTC**
Fix in review: https://dev.vaadin.com/review/#/c/11576/

**Comment by makoivis** [comment]
**Modified by elmot on 16 Jul 2015 08:27 UTC**
