### ISSUE TITLE
Cannot create new vaadin project

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#566]
**Reported by mwisnicki on 2 Sep 2013 03:16 UTC**
Eclispe 4.3 for JEE, fresh workspace, JEE perspective.

Clicking "New\Vaadin 7 project" from context menu does not work.
Following is logged:

```
eclipse.buildId=4.3.0.I20130605-2000
java.version=1.7.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=pl_PL
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -data W:\workspaces\tmp1 -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

Error
Mon Sep 02 05:12:13 CEST 2013
Unhandled event loop exception

java.lang.IllegalArgumentException: Could not select preset "com.vaadin.integration.eclipse.presetv7j16s30". One or more required of the required facets are not visible.
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.setSelectedPreset(FacetedProjectWorkingCopy.java:1068)
    at com.vaadin.integration.eclipse.wizards.VaadinProjectWizard.setRuntimeAndDefaultFacets(VaadinProjectWizard.java:72)
    at org.eclipse.wst.web.ui.internal.wizards.NewProjectDataModelFacetWizard.createPageControls(NewProjectDataModelFacetWizard.java:150)
    at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:736)
    at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:608)
    at org.eclipse.jface.window.Window.create(Window.java:432)
    at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1104)
    at org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(WizardShortcutAction.java:95)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
```

If I open "New\Project..." wizard I can select "Vaadin 7 Project" and proceed by clicking "Next" two times (first time generates exception as above).

Migrated-From: http://dev.vaadin.com//ticket/12484

**Comment by makoivis** [comment]
**Modified by mwisnicki on 2 Sep 2013 03:16 UTC**

**Comment by makoivis** [comment]
**Comment by mwisnicki on 2 Sep 2013 03:20 UTC**
It works if I remove Google App Engine from Server runtimes.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:03 UTC**

**Comment by makoivis** [comment]
**Comment by Marlon Richert on 29 Jan 2014 14:48 UTC**
This happens when there is a runtime configured that does not support the Servlet 3.0 facet. For example, Apache Tomcat 6.

**Comment by makoivis** [comment]
**Modified by Marlon Richert on 29 Jan 2014 14:49 UTC**

**Comment by makoivis** [comment]
**Modified by Henri Sara on 30 Jan 2014 07:15 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 30 Jan 2014 07:19 UTC**
Confirmed as happening with various runtimes that do not support Servlet 3.0 (Dynamic Web Module facet version 3.0)

**Comment by makoivis** [comment]
**Modified by Saulis on 8 May 2014 10:55 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:40 UTC**

**Comment by makoivis** [comment]
**Modified by antti on 12 May 2014 11:19 UTC**

**Comment by makoivis** [comment]
**Modified by Saulis on 26 May 2014 10:44 UTC**

**Comment by makoivis** [comment]
**Modified by Saulis on 7 Jul 2014 11:42 UTC**

**Comment by makoivis** [comment]
**Modified by Juuso Valli on 8 Jul 2014 14:11 UTC**

**Comment by makoivis** [comment]
**Modified by Leif Astrand on 10 Jul 2014 10:51 UTC**

**Comment by makoivis** [comment]
**Modified by Juuso Valli on 23 Jul 2014 08:02 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 17 Aug 2014 16:14 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
