### ISSUE TITLE
ClassCastException from Eclipse Plugin when compiling theme

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#567]
**Reported by peterl1084 on 10 Sep 2013 07:20 UTC**
When compiling theme with latest Eclipse Plugin (2.2.0.201306261112) I get a popup dialog showing ClassCastException and following stacktrace in the error log

```
java.lang.ClassCastException: org.eclipse.core.internal.resources.File cannot be cast to org.eclipse.core.resources.IFolder
    at com.vaadin.integration.eclipse.handlers.CompileThemeHandler.compileAllThemes(CompileThemeHandler.java:118)
    at com.vaadin.integration.eclipse.handlers.CompileThemeHandler$1.run(CompileThemeHandler.java:74)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Migrated-From: http://dev.vaadin.com//ticket/12539

**Comment by makoivis** [comment]
**Comment by peterl1084 on 10 Sep 2013 07:22 UTC**
In my project I have two themes under the VAADIN/themes folder

**Comment by makoivis** [comment]
**Comment by peterl1084 on 17 Oct 2013 09:47 UTC**
Same problem seems to occur in some situations when workspace is cleared and the Addon Style Builder is running as part of building workspace.

Red popup error dialog is shown with following content:

```
Errors occurred during the build.
Errors running builder 'Addon Styles Builder' on project '[name](Project)'.
org.eclipse.core.internal.resources.File cannot be cast to org.eclipse.core.resources.IFolder
```

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:03 UTC**

**Comment by makoivis** [comment]
**Comment by teemusa on 2 Jan 2014 08:00 UTC**
Looks like this is caused by a file (not a folder) in themes folder.

**Comment by makoivis** [comment]
**Modified by Leif Astrand on 3 Jan 2014 06:56 UTC**

**Comment by makoivis** [comment]
**Modified by Henri Sara on 3 Jan 2014 09:58 UTC**

**Comment by makoivis** [comment]
**Comment by a.filler on 6 Apr 2014 16:14 UTC**
I was able to fix it on my Mac by deleting the .DS_store file from the template folder. - Quite easy when you know that the file is causing the problem.

hth - Andreas

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:40 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
