### ISSUE TITLE
New Project causes exception when Google App Engine runtime is the only available server runtime

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#579]
**Reported by Artur Signell on 4 Dec 2013 09:41 UTC**
Installing the Vaadin plug-in and the GWT plug-ing (including Google App Engine) in a clean Eclipse causes problem when creating a new Vaadin 7 project. When selecting "New Vaadin 7 project" the wizard is only partly rendered and the following is logged to the error log:

```
java.lang.IllegalArgumentException: Could not select preset "com.vaadin.integration.eclipse.presetv7j16s30". One or more required of the required facets are not visible.
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.setSelectedPreset(FacetedProjectWorkingCopy.java:1068)
    at com.vaadin.integration.eclipse.wizards.VaadinProjectWizard.setRuntimeAndDefaultFacets(VaadinProjectWizard.java:72)
    at org.eclipse.wst.web.ui.internal.wizards.NewProjectDataModelFacetWizard.createPageControls(NewProjectDataModelFacetWizard.java:150)
    at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:736)
    at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1182)
    at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1241)
    at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1238)
    at org.eclipse.jface.wizard.WizardDialog$8.run(WizardDialog.java:1227)
```

Project creation can be completed by clicking next but an extra dummy servlet class is added to the project. 

All the problems seem to be caused by having a default target runtime of "Google App Engine". This adds the Google App Engine facet by default which causes the dummy servlet to be created. Also causes the exception in the error log. 

With a "<none>" target runtime or with some other target runtime available this is not an issue.

Migrated-From: http://dev.vaadin.com//ticket/13045

**Comment by makoivis** [comment]
**Comment by Henri Sara on 30 Jan 2014 07:17 UTC**
Duplicate of #12484

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:40 UTC**
