### ISSUE TITLE
License checker fails when run from eclipse plugin

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#616]
**Reported by Thomas Mattsson on 20 Jan 2015 17:03 UTC**
In some cases the license checker fails to find the license file when running compilation from the eclipse plugin under Windows 7/Java7. Maven compilation works fine. 

It happens because the URI passed to CvalChecker.readKeyFromFile is in the format "file://C:/.." that results in an exception:

```
java.net.UnknownHostException: C
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:157)
at java.net.Socket.connect(Socket.java:579)
at java.net.Socket.connect(Socket.java:528)
at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:943)
at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:903)
at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:998)
at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:984)
at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:393)
at java.net.URL.openStream(URL.java:1037)
at miaprova.main(miaprova.java:49)
```

According to Johannes Dahlstrm, the path should be "file:///C:/..." instead. For some reason this works on e.g. Annas computer (compiling Charts; we tried Spreadsheet).

Migrated-From: http://dev.vaadin.com//ticket/16381

**Comment by makoivis** [comment]
**Comment by proaccountapp on 20 Jan 2015 18:12 UTC**
Updated prioritization date.

**Comment by makoivis** [comment]
**Modified by amahdy on 20 Jan 2015 23:09 UTC**

**Comment by makoivis** [comment]
**Modified by Markus Koivisto on 27 Jan 2015 08:27 UTC**

**Comment by makoivis** [comment]
**Modified by amahdy on 27 Jan 2015 12:15 UTC**

**Comment by makoivis** [comment]
**Comment by amahdy on 29 Jan 2015 13:32 UTC**
Unable to get the 'file:///C:/' or 'file://C:/' from the standard Vaadin code.
I tested on VM and on Anna's machine. The output is always 'file:/C:/'

Here is a simple test code that replicate how the URL is formed in CvalChecker. Can we run this in client's machine to see the output?

```
import java.io.File;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;

public class Main {

    public static void main(String args[]) throws MalformedURLException, URISyntaxException {

        String licenseName = "licname";

        String dotLicenseName = "." + licenseName;
        String userHome = System.getProperty("user.home");

        System.out.println("======== this should form a fully formated protocol: 'file:///'");
        System.out.println(Paths.get(new File(userHome, dotLicenseName).toURI()).toUri());
        System.out.println("======== this should form a normal URI: 'file:/'");
        System.out.println(new File(userHome, dotLicenseName).toURI());
        System.out.println("======== this should form a normal URL: 'file:/'");
        System.out.println(new File(userHome, dotLicenseName).toURI().toURL());
        System.out.println("======== do we have any output here?");
        System.out.println(URL.class.getResource("/" + dotLicenseName));
    }
}

```

**Comment by makoivis** [comment]
**Comment by amahdy on 3 Feb 2015 14:50 UTC**
Unable to reproduce. No longer working on this too.

**Comment by makoivis** [comment]
**Comment by Henri Kerola on 10 Feb 2015 23:44 UTC**
Could this issue be as simple as the user is using an old version of CvalChecker? Because the following change set fixes exactly this same issue:

https://github.com/vaadin/vaadin/commit/3a9aa4c277cbfb956511a1c25e984bb2e2c65476

**Comment by makoivis** [comment]
**Comment by Henri Kerola on 19 Feb 2015 01:38 UTC**
Closing this, please make sure that you are using the latest version. If still happens with the latest version, please reopen.
