### ISSUE TITLE
Eclipse plugin scans for Vaadin version in non-vaadin projects

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#633]
**Reported by bogdanudrescu on 30 Sep 2015 08:42 UTC**
In a workspace with non Vaadin projects and regular projects opened, I get this exception pretty often.

```
org.eclipse.core.runtime.CoreException: Unable to find WEB-INF/lib folder. Ensure the project is a dynamic web project.
    at com.vaadin.integration.eclipse.util.ErrorUtil.newCoreException(ErrorUtil.java:141)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getWebInfLibFolder(ProjectUtil.java:110)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getVaadinLibraryInProject(ProjectUtil.java:376)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getVaadinLibraryVersion(ProjectUtil.java:351)
    at com.vaadin.integration.eclipse.background.CheckVaadinVersionsJob.getVaadinProjects(CheckVaadinVersionsJob.java:100)
    at com.vaadin.integration.eclipse.background.CheckVaadinVersionsJob.run(CheckVaadinVersionsJob.java:63)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

Migrated-From: http://dev.vaadin.com//ticket/19041

**Comment by makoivis** [comment]
**Comment by John Ahlroos on 11 Dec 2015 09:32 UTC**
When you have multiple non-java projects in your workspace this error is thrown for every non-java project.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 11 Dec 2015 10:33 UTC**
The plug-in should not log errors in such cases.
Scanning might be needed even for such Java projects as not all projects using Vaadin have the Vaadin or Dynamic Web Module facet, but no errors should be reported in those cases.

**Comment by makoivis** [comment]
**Comment by John Ahlroos on 11 Dec 2015 14:13 UTC**
https://dev.vaadin.com/review/#/c/12675

**Comment by makoivis** [comment]
**Comment by Henri Sara on 14 Dec 2015 10:05 UTC**
Fixed - might also need to be reapplied to https://dev.vaadin.com/review/#/c/12477/ when it is merged.

**Comment by makoivis** [comment]
**Modified by Henri Sara on 14 Dec 2015 10:05 UTC**
