### ISSUE TITLE
New component fails if there is no widgetset

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#64]
**Reported by Artur Signell on 5 Mar 2009 13:56 UTC**

```
java.lang.IllegalArgumentException: Index out of bounds
at org.eclipse.swt.SWT.error(SWT.java:3761)
at org.eclipse.swt.SWT.error(SWT.java:3695)
at org.eclipse.swt.SWT.error(SWT.java:3666)
at org.eclipse.swt.widgets.Widget.error(Widget.java:463)
at org.eclipse.swt.widgets.Combo.getItem(Combo.java:644)
at com.itmill.toolkit.integration.eclipse.wizards.NewComponentWizardPage.createClientSideControls(NewComponentWizardPage.java:204)
at com.itmill.toolkit.integration.eclipse.wizards.NewComponentWizardPage.createControl(NewComponentWizardPage.java:136)
at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1147)
at org.eclipse.jface.wizard.WizardDialog.access$2(WizardDialog.java:1139)
at org.eclipse.jface.wizard.WizardDialog$4.run(WizardDialog.java:1128)
```

Migrated-From: https://dev.vaadin.com/ticket/2727

**Comment by makoivis** [comment]
**Comment by Henri Sara on 9 Apr 2009 05:33 UTC**
Fixed in [7372].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 24 Sep 2009 15:08 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:43 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
