### ISSUE TITLE
Vaadin 7.6.2 Eclipse Plugin annoying with "Unable to find WEB-INF/lib folder" in closed and non-Vaadin projects.

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#641]
**Reported by enver on 3 Feb 2016 15:07 UTC**

Vaadin 7.6.2 Eclipse Plugin annoying with "Unable to find WEB-INF/lib folder" in closed and non-Vaadin projects.

Migrated-From: http://dev.vaadin.com/ticket/19548

**Comment by samie** [comment]
Looks like this happens not only for closed projects, but all multimodule Maven projects:

Could not check Vaadin version in project multimodule-production

org.eclipse.core.runtime.CoreException: Unable to find WEB-INF/lib folder. Ensure the project is a dynamic web project.
    at com.vaadin.integration.eclipse.util.ErrorUtil.newCoreException(ErrorUtil.java:141)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getWebInfLibFolder(ProjectUtil.java:214)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getVaadinLibraryInProject(ProjectUtil.java:481)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getVaadinLibraryVersion(ProjectUtil.java:456)
    at com.vaadin.integration.eclipse.notifications.jobs.nightly.NightlyCheckJob.getVaadinUpgrades(NightlyCheckJob.java:215)
    at com.vaadin.integration.eclipse.notifications.jobs.nightly.NightlyCheckJob.checkProjects(NightlyCheckJob.java:113)
    at com.vaadin.integration.eclipse.notifications.jobs.nightly.NightlyCheckJob.run(NightlyCheckJob.java:58)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
