### ISSUE TITLE
Unable to find WEB-INF/lib folder

### ISSUE THREAD

**Issue by johndevs** [vaadin/eclipse-plugin-legacy#691]
The version checker of the Vaadin plugin is currently assuming there is a WEB-INF/lib folder. 

This is not always the case and the version checker will throw the following exception:

```
org.eclipse.core.runtime.CoreException: Unable to find WEB-INF/lib folder. Ensure the project is a dynamic web project.
    at com.vaadin.integration.eclipse.util.ErrorUtil.newCoreException(ErrorUtil.java:141)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getWebInfLibFolder(ProjectUtil.java:110)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getVaadinLibraryInProject(ProjectUtil.java:376)
    at com.vaadin.integration.eclipse.util.ProjectUtil.getVaadinLibraryVersion(ProjectUtil.java:351)
    at com.vaadin.integration.eclipse.background.CheckVaadinVersionsJob.getVaadinProjects(CheckVaadinVersionsJob.java:100)
    at com.vaadin.integration.eclipse.background.CheckVaadinVersionsJob.run(CheckVaadinVersionsJob.java:63)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by hesara** [comment]
This doesn't seem to be from the current version of the Vaadin Eclipse plug-in - 3.0.0.alpha1 doesn't even have the class CheckVaadinVersionsJob. Several cases of problematic calls to ProjectUtil.get*() were fixed for alpha1 so that null is returned and checked for, or the version check is not performed at all in a project of a wrong type, but I'm not sure if there is still a problematic one left there.

**Comment by johndevs** [comment]
Looks like this was only a issue with the old version, did an update for beta1 and at least with a short testing run not seeing this anymore.
