### ISSUE TITLE
Error message at startup in Eclipse Neon

### ISSUE THREAD

**Issue by ropoman** [vaadin/eclipse-plugin-legacy#708]
An internal error occurred during: "Fetch all notifications".
org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray

**Comment by ghost** [comment]
I have this error too.

**Comment by Artur-** [comment]
Does this problem still occur?

**Comment by aschoenherr** [comment]
I am also experiencing this error on eclipse start-up.
it isn't preventing me from running the application or my tests, but occurs 100% of the time when I initially open the application. not a big deal, but found this when searching so I figured I should mention that I also have this occuring.

Eclipse release Neon.1a Release(4.6.1) build id: 20161007-1200
Windows 10 Pro x64, Build 14393.693, Version 1607

thanks

**Comment by ospinakamilo** [comment]
This problem is currently happen for me. I just did a fresh install of Eclipse and after installing vaadin plugin the message start appearing on every start-up.

OS: Mac Os Sierra 10.12.2

Eclipse Java EE IDE for Web Developers.
Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by StevenRieger** [comment]
I am getting this as well.  
Windows 10 64 Bit

Eclipse Java EE IDE for Web Developers.
Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600

Any resolution to this?

**Comment by denis-anisimov** [comment]
The issue is most likely the consequence of unexpected answer from the server.
The plugin code expects an array of notifications but it gets something that is not an array.
The code should be fixed to be able to handle the unexpected answer but it's also worth to understand why server returns this kind of answer instead of a list of notifications.

**Comment by SenorDumpfbacke** [comment]
Had the same Problem with:

Win 7 (64 bit)
Version: Neon Release (4.6.0)
Build id: 20160613-1800
Java 1.8.0_91

**Resolution**: Its the "Vaadin Plug-in for Eclipse" (in my case V3.0.0) that was causing the Problem. Simply reinstalling did NOT work. Have deinstalled it now permanently, didn't use it anyways.

**Comment by jdamianb** [comment]
I have the same problem :/ I just started using the framework and got the exact problem.

System:
Lenovo T420
Ubuntu 16.10 (64bit)
Eclipse JEE (4.6.1)
Java 1.8.0

But anyway, great framework!

**Comment by Lienix** [comment]
I have the same problem after installing  "Vaadin Plug-in for Eclipse" (in my case also V3.0.0) with

Eclipse IDE Neon.1a Release (4.6.1)
jre1.8.0_121
running on Windows 7

**Comment by jdamianb** [comment]
Its weird but today I opened eclipse to work and the error is not there anymore and the notifications from Vaadin is working. I checked the eclipse and ubuntu version and nothing had changed.

I hope the others can get an explanation why this happens.

**Comment by ospinakamilo** [comment]
Indeed is also working fine for me now, nothing have change.

**Comment by Lienix** [comment]
Hi, for me it is also working fine now - without changing anything from my side!!!
I hope also for an explanation.

**Comment by ropoman** [comment]
I updated to vaadin 4.0.0 and designer 2.0.0 and I am disappointed that this error is still there

**Comment by ropoman** [comment]
I updated to neon.3, created a new workspace and everything was working well ..... and then I signed on to vaadin after clicking on the red bell in the bottom right corner and whoosh:
An internal error occurred during: "Fetch all notifications".
org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray

After signing out in the preferences the error is gone

**Comment by FiruzzZ** [comment]
The error is still present, I just downloaded Neon 3 ((4.6.3)Build id: 20170314-1500) and Vaadin's plugin 4.0.0

**Comment by UlukmyrzaTegin** [comment]
I also have this situation, I am very disappointed that this bug is still there. 
In my case:  IDE Eclipse Neon 3 - plugin Vaadin 4.0.0 and designer 2.0.0

**Comment by markposterone** [comment]
I am getting the same (or similar) error: Windows 7 / 64 bit, Eclipse Oxygen 2 : 
An internal error occurred during: "Fetch all notifications". Argument not valid. It happens on each startup and each time I click on Vaadin bell in the corner.

**Comment by mimarko** [comment]
Same error on mac os x / eclipse oxygen / vaadin notification icon in the right bottom corner

**Comment by tsuoanttila** [comment]
The `Argument not valid` you see is related to the notifications yes, but thrown actually from SWT image library. My first guess would be that there's an image in one of the notifications that is of an unsupported type. Trying to get this fixed ASAP.

**Comment by nandesh553** [comment]
Same was happening with me ... It was working fine on one system, but wasn't working on other. I thought it might be an installation error. Later when i went on former system(where it was working) it showed the same error on booting. This shows that it is the repo error. There must be something wrong with there server at that time. I hope it gets fixed soon.

**Comment by harrwiss-swt** [comment]
Same problem here as well (since view days) when clicking on the notification icon - this shows in the Eclipse error log (Neon.3 4.6.3):
![grafik](https://user-images.githubusercontent.com/16510653/36793637-31d0c264-1c9e-11e8-98d5-2b5bcbb0156c.png)

**Comment by focbenz** [comment]
Our team is also affected since around Wednesday this week - like @tsuoanttila mentioned it seems to be related to a problem with ImageData. 
`java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:426)
	at org.eclipse.swt.graphics.ImageData.scaledTo(ImageData.java:1118)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.downloadImage(NotificationsService.java:674)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.getImage(NotificationsService.java:610)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.registerImage(NotificationsService.java:568)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.ensureImageRegistered(NotificationsService.java:561)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.downloadImages(NotificationsService.java:547)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.downloadImages(NotificationsService.java:157)
	at com.vaadin.integration.eclipse.notifications.jobs.FetchNotificationsJob.run(FetchNotificationsJob.java:80)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)`

**Comment by tsuoanttila** [comment]
Released a new version `4.0.2` that has a fix for this. See also related ticket #749

**Comment by mpittkin** [comment]
I just installed Oxygen.3 (4.7.3). Installed Vaadin plugin 4.0.2 first thing and am getting the following error:
An internal error occurred during: "Fetch all notifications".
java.lang.NullPointerException.

Error log looks like this:
![image](https://user-images.githubusercontent.com/18724853/38407250-99cc4270-392d-11e8-85a9-f59a29d65e7e.png)

**Comment by martinisraelsen** [comment]
There was a period of time where the notifications were working, but not I'm getting the "Fetch all notifications" error again.

Eclipse: Oxygen.3a Release (4.7.3a)
Vaadin Plugin 4.0.2

```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:426)
	at org.eclipse.swt.graphics.ImageData.scaledTo(ImageData.java:1118)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.downloadImage(NotificationsService.java:674)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.getImage(NotificationsService.java:610)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.registerImage(NotificationsService.java:568)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.ensureImageRegistered(NotificationsService.java:561)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.downloadImages(NotificationsService.java:547)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.downloadImages(NotificationsService.java:157)
	at com.vaadin.integration.eclipse.notifications.jobs.FetchNotificationsJob.run(FetchNotificationsJob.java:80)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

and 


```
org.eclipse.swt.SWTException: Unsupported or unrecognized format
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.internal.image.FileFormat.load(FileFormat.java:84)
	at org.eclipse.swt.graphics.ImageLoader.load(ImageLoader.java:146)
	at org.eclipse.swt.graphics.ImageDataLoader.load(ImageDataLoader.java:22)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:332)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.getImage(NotificationsService.java:595)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.registerImage(NotificationsService.java:568)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.ensureImageRegistered(NotificationsService.java:561)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.downloadImages(NotificationsService.java:547)
	at com.vaadin.integration.eclipse.notifications.model.NotificationsService.downloadImages(NotificationsService.java:157)
	at com.vaadin.integration.eclipse.notifications.jobs.FetchNotificationsJob.run(FetchNotificationsJob.java:80)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

```
