### ISSUE TITLE
NPM version check exceptions at start of Spring Boot starter

### ISSUE THREAD

**Issue by alump** [vaadin/eclipse-plugin-legacy#775]
**Setup:**
- Preview Eclipse plugin (for 14 support)
- Eclipse 2019-06 (4.12.0)
- MacOS 10.14.5
- Amazon Corretto 11

**Steps:**
1. New Vaadin project, use Spring Boot starter
2. Run `mvn spring-boot:run`

**Expected outcome:**
Application starts without exceptions

**Actual outcome:**
Something goes wrong at npm version check. Application starts, but I think output should be cleaned up if it's not fatal. Gives bad first impression. 

`
com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of npm.Using command /usr/local/bin/npm --version
	at com.vaadin.flow.server.frontend.FrontendUtils.getVersion(FrontendUtils.java:498) ~[flow-server-2.0.1.jar:2.0.1]
	at com.vaadin.flow.server.frontend.FrontendUtils.validateNodeAndNpmVersion(FrontendUtils.java:397) ~[flow-server-2.0.1.jar:2.0.1]
	at com.vaadin.flow.server.DevModeHandler.<init>(DevModeHandler.java:137) ~[flow-server-2.0.1.jar:2.0.1]
	at com.vaadin.flow.server.DevModeHandler.createInstance(DevModeHandler.java:277) ~[flow-server-2.0.1.jar:2.0.1]
	at com.vaadin.flow.server.DevModeHandler.start(DevModeHandler.java:220) ~[flow-server-2.0.1.jar:2.0.1]
	at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:182) ~[flow-server-2.0.1.jar:2.0.1]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:284) ~[vaadin-spring-12.0.1.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4680) ~[tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5150) ~[tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377) ~[tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367) ~[tomcat-embed-core-9.0.17.jar:9.0.17]
...`

I haven't seen this issue on Intellij IDEA

**Comment by alump** [comment]
```
alumps-mbp15:~ alump$ /usr/local/bin/npm --version
6.9.0
```
