### ISSUE TITLE
Exception when changing Vaadin jar versions

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#8]
**Reported by Artur Signell on 1 Oct 2009 13:23 UTC**
On the first attempt to change jar version (in project properties) from 6.1.1 to 6.1.nightly-20090930-c8998.jar I got:

```
java.lang.reflect.InvocationTargetException
at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:421)
at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:507)
at com.vaadin.integration.eclipse.properties.VaadinVersionPropertyPage.performOk(Unknown Source)
at org.eclipse.jface.preference.PreferenceDialog$13.run(PreferenceDialog.java:964)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.core.runtime.Platform.run(Platform.java:888)
at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:48)
at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:944)
at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:453)
at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:624)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:228)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1003)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3880)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3473)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
at org.eclipse.jface.window.Window.open(Window.java:801)
at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:157)
at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1003)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3880)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3473)
at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2405)
at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2369)
at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2221)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:500)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:493)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:113)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:194)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:368)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:559)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:514)
at org.eclipse.equinox.launcher.Main.run(Main.java:1311)
at org.eclipse.equinox.launcher.Main.main(Main.java:1287)
Caused by: org.eclipse.jdt.internal.core.ClasspathEntry$AssertionFailedException: Library path cannot be null
at org.eclipse.jdt.core.JavaCore.newLibraryEntry(JavaCore.java:4034)
at org.eclipse.jdt.core.JavaCore.newLibraryEntry(JavaCore.java:3917)
at org.eclipse.jdt.launching.JavaRuntime.newArchiveRuntimeClasspathEntry(JavaRuntime.java:628)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.updateLaunchClassPath(Unknown Source)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.updateLaunchClassPath(Unknown Source)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.updateVaadinLibraries(Unknown Source)
at com.vaadin.integration.eclipse.properties.VaadinVersionPropertyPage$1.run(Unknown Source)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Root exception:
org.eclipse.jdt.internal.core.ClasspathEntry$AssertionFailedException: Library path cannot be null
at org.eclipse.jdt.core.JavaCore.newLibraryEntry(JavaCore.java:4034)
at org.eclipse.jdt.core.JavaCore.newLibraryEntry(JavaCore.java:3917)
at org.eclipse.jdt.launching.JavaRuntime.newArchiveRuntimeClasspathEntry(JavaRuntime.java:628)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.updateLaunchClassPath(Unknown Source)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.updateLaunchClassPath(Unknown Source)
at com.vaadin.integration.eclipse.util.VaadinPluginUtil.updateVaadinLibraries(Unknown Source)
at com.vaadin.integration.eclipse.properties.VaadinVersionPropertyPage$1.run(Unknown Source)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

```

On the second attempt (just clicking ok again) it went fine.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 1 Oct 2009 13:26 UTC**
This seems to be reproducible when the jar is downloaded in the same properties dialog.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 2 Oct 2009 11:06 UTC**
Could not reproduce this using the latest plugin version.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**
